version: '3.9'

services:
  api-producer:
    container_name: api-producer
    build:
      context: ./api-producer
      dockerfile: Dockerfile
    environment:
      RABBIT_USER: guest
      RABBIT_PASS: guest
      RABBIT_HOSTNAME: rabbitmq
      RABBIT_PORT: 5672
      PORT: 8080
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    volumes:
      - ./scripts/shell/wait-for-it.sh:/root/wait-for-it.sh
    entrypoint: ["./wait-for-it.sh", "rabbitmq:5672", "--", "./api-producer"]

  database-service-consumer:
    container_name: database-service-consumer
    build:
      context: ./database-service-consumer
      dockerfile: Dockerfile
    environment:
      DATABASE: host=postgres port=5432 user=postgres password=postgres dbname=mydb sslmode=disable
      RABBIT_USER: guest
      RABBIT_PASS: guest
      RABBIT_HOSTNAME: rabbitmq
      RABBIT_PORT: 5672
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./scripts/shell/wait-for-it.sh:/root/wait-for-it.sh
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "rabbitmq:5672", "--", "./database-service-consumer"]

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    volumes:
      - ./scripts/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5440:5432"

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
