version: '3.0'

services:
  api-producer:
    build: ./api-producer/
    working_dir: /go/src/github.com/golang-rabbit-sample/api-producer
    container_name: api-producer
    volumes:
      - ./scripts/shell:/go/src/github.com/golang-rabbit-sample/api-producer/scripts
    environment: 
      RABBIT_USER: guest
      RABBIT_PASS: guest
      RABBIT_HOSTNAME: rabbitmq
      RABBIT_PORT: 5672
    depends_on: 
      - rabbitmq
    ports: 
      - "8889:8889"
    command: ["./scripts/wait-for-it.sh", "rabbitmq:5672", "--", "go", "run", "cmd/api-producer/main.go"]

  database-service-consumer:
    build: ./database-service-consumer/
    working_dir: /go/src/github.com/golang-rabbit-sample/database-service-consumer
    container_name: database-service-consumer
    volumes:
      - ./scripts/shell:/go/src/github.com/golang-rabbit-sample/database-service-consumer/scripts
    environment: 
      DATABASE: host=postgres port=5432 user=postgres password=postgres dbname=mydb sslmode=disable
      RABBIT_USER: guest
      RABBIT_PASS: guest
      RABBIT_HOSTNAME: rabbitmq
      RABBIT_PORT: 5672
    depends_on: 
      - postgres
      - rabbitmq
    command: ["./scripts/wait-for-it.sh", "postgres:5432", "--", "./scripts/wait-for-it.sh", "rabbitmq:5672", "--", "go", "run", "cmd/database-service-consumer/main.go"]

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    volumes: 
      - ./scripts/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5440:5432"

  rabbitmq:
    image: rabbitmq:3.6.0-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"